[phases.setup]
nixPkgs = ['python3']

[phases.install]
cmds = ['python -m venv --copies /opt/venv', '. /opt/venv/bin/activate && pip install -r requirements.txt']

[phases.build]
cmds = ['echo "Build completed"']

[start]
cmd = '. /opt/venv/bin/activate && python bot.py'

